apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: a2hnj2xxn-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/a2hnj2xxn-dotnet-basic